# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20
